base.yaml
static/v2board_esp32_d1_mini.yaml
static/v2board_esp8266_d1_mini_lite.yaml

Currently the `ratgdo` component in `base.yaml` always uses the default pin values. 
This results in compilation failure for boards that don't have the `Dx` pin aliases and doesn't allow for pins to be customized.

Use the ratgdo pins configured in the substitutions section

---

base.yaml
components/ratgdo/ratgdo.cpp

A loop cycle in esphome happens once about every 16ms and an opener command on serial is transmitted in about 16ms as well, so by the time a byte can be read on the serial line the whole command can probably be read. This change reads the whole command at once (or as much as possible) instead of a byte on every loop cycle.

Speed up serial line reads

---

base.yaml
components/ratgdo/ratgdo.cpp
components/ratgdo/ratgdo.h

This fixes the soft reboot when hammering the light. There is some risk that we could increment the counter > 5 in 5s and than get an unhandled reset, but that seems really low.  I think its better to fix that crash and take a little bit of risk there.

Fix crash when flash is written too frequently

---

base.yaml
components/ratgdo/ratgdo.cpp
components/ratgdo/ratgdo.h
static/v2board_esp8266_d1_mini_lite.yaml

Currently the door stop button actually send a door toggle command, which does stop the door when it's opening, but it reverses the direction when the door closes. 
I found that there is a stop command that actually stops the door in both cases. It's still possible to reverse the direction while closing the door by using the "open" button.

Use door stop command in place of toggle

---

base.yaml
components/ratgdo/cover/ratgdo_cover.cpp
components/ratgdo/cover/ratgdo_cover.h
components/ratgdo/number/__init__.py
components/ratgdo/number/ratgdo_number.cpp
components/ratgdo/number/ratgdo_number.h
components/ratgdo/ratgdo.cpp
components/ratgdo/ratgdo.h
components/ratgdo/ratgdo_child.cpp
components/ratgdo/ratgdo_child.h
static/v2board_esp8266_d1_mini_lite.yaml

This implements door position control using the time it takes the door to open/close. It's obviously open-loop, since there's no feedback from the GDO until the door hits the fully opened / closed positions, it optimistically syncs the door position in the UI every 0.5s .
However, I find it quite useful, many times I want to open the garage door just a little (10-15%) to let some air in and now I can do it in one step instead of opening&stopping it.
It adds two configuration parameters, opening_duration & closing_duration, probably the same in most cases, but can be different if needed. If these are not configured, it assumes middle position 50% as before.

Door position control

---

README.md
base.yaml
components/ratgdo/__init__.py
components/ratgdo/automation.h
components/ratgdo/cover/ratgdo_cover.cpp
components/ratgdo/light/ratgdo_light_output.cpp
components/ratgdo/number/ratgdo_number.cpp
components/ratgdo/number/ratgdo_number.h
components/ratgdo/ratgdo.cpp
components/ratgdo/ratgdo.h
static/index.html
static/v2board_esp8266_d1_mini_lite.yaml

This moves the global preferences from the main ratgdo class to ratgdo_number which makes the code simpler and also changes the storage type from hard-coded values to the component's `get_object_id_hash()`.
I also persists the door position between reboots/upgrades.
**NOTE**: this is a breaking changes with respect to the values stored in flash, the rolling code, opening/closing times need to be saved/re-entered.

Make storing persistent state the resposibility of ratgdo_number

---

components/ratgdo/ratgdo.cpp

In RATGDOComponent::setup() call the ESPHome code to attach_interrupt() before software serial begin().  This allows ESPHome to call IDF gpio_install_isr_service() without error.
Tested on ESP32, fixes operation of the obstruction sensor from #36.  Still get an error in the logs presumably when software serial tries to call gpio_install_isr_service() during setup but connection to garage door works properly.
Needs to be tested on a ESP8266.

Fix obstruction isr for ESP32

---

base.yaml
components/ratgdo/ratgdo.cpp
components/ratgdo/ratgdo.h

Fall back to reading the obstruction state if the obstruction pin is disabled.
This is a subpar experience currently but better than nothing.

feat: add support for disabling the obstruction pin

---

base.yaml
components/ratgdo/ratgdo.cpp
components/ratgdo/ratgdo.h

Make obstruction detection ignore spurrious detections when sensors awake from sleep mode, for example when light is turned on.
Fixes #40.

Make obstruction detection ignore spurrious detections 

---

base.yaml
components/ratgdo/callbacks.h
components/ratgdo/observable.h
components/ratgdo/ratgdo.cpp
components/ratgdo/ratgdo.h
static/v2board_esp8266_d1_mini_lite.yaml

This adds two callbacks for command sent and door status received to ensure more predictable sequencing of events. 
For example, one case I encountered was when sending a door command (which is emulating a button press and a button release 100ms later), simultaneously with some motion events that caused the button press to be delayed, causing it to be too close or after the button release and thus ignored. This add a callback for when a door command was actually sent and only sends the next command then (instead of a fixed delay).
The door state callback is useful for things like sending a door command and waiting for a status message until another door command can be sent. This PR adds an `ensure_door_command` which can be used to ensure a command is actually received by the opener, …

Door opening/close relliability updates

---

components/ratgdo/number/ratgdo_number.cpp
components/ratgdo/ratgdo.cpp
components/ratgdo/ratgdo.h

This should fix #89 (and reverts #88). It enforces the client_id to always end with `0x539`, but randomizes the two bytes before that. As an added benefit, it's easy to recognize the esp client_id (always ends in `0x539`).
Also fixes a bug in ratgdo_number where the component's state was not updated when the number value was changed (for example changing the client_id and refreshing/re-opening the web page or the HA device info page would show the old client_id, although the flash and ratgdo used the new one).

Fix issue #89 by imposing some limits on the random client_id

---

components/ratgdo/number/ratgdo_number.cpp

Restrict the range of client_ids so that we don't get conversion errors due to https://github.com/esphome/issues/issues/2875

Add limits on the range of client_id values

---

static/v25board_esp32_d1_mini.yaml
static/v25board_esp8266_d1_mini_lite.yaml

reported in https://github.com/ratgdo/esphome-ratgdo/issues/96#issuecomment-1799536674

fix package import urls for the v25 boards

---

.github/workflows/build.yml

1.2.3 stopped working with no other changes.. lets hope 1.2.9 fixes it
otherwise it might be https://github.com/actions/upload-artifact/issues/472

Bump actions/deploy-pages to 1.2.9

---

static/v25iboard.yaml

fix: v2.5i boards should use d1_mini

---

static/index.html

Images still aren't great, but at least not broken 😉   We can switch them out for something better later

Fix missing esp32 images

---

static/v25board_esp8266_d1_mini.yaml

I think static/v25board_esp8266_d1_mini.yaml needs a board definition update to reflect that the board is d1_mini now.

Change board in v25board_esp8266_d1_mini.yaml to d1_mini

---

base.yaml
base_drycontact.yaml
base_secplusv1.yaml
static/v25board_esp32_d1_mini.yaml
static/v25board_esp32_d1_mini_secplusv1.yaml
static/v25board_esp8266_d1_mini.yaml
static/v25board_esp8266_d1_mini_lite.yaml
static/v25board_esp8266_d1_mini_lite_secplusv1.yaml
static/v25board_esp8266_d1_mini_secplusv1.yaml
static/v25iboard.yaml
static/v25iboard_drycontact.yaml
static/v25iboard_secplusv1.yaml
static/v2board_esp32_d1_mini.yaml
static/v2board_esp32_lolin_s2_mini.yaml
static/v2board_esp8266_d1_mini.yaml
static/v2board_esp8266_d1_mini_lite.yaml

Original PR https://github.com/ratgdo/esphome-ratgdo/pull/291
Moving the OTA block to the base of the respective
esphome-ratgdo board.
Starting with version 2024.6.0, at least one platform must
be specified for 'OTA'; add 'platform: esphome' for
original OTA functionality.
Fixes: #289
Signed-off-by: Flavio Fernandes <flavio@flaviof.com>

OTA: Moving to base.yamls and adding ESPHome platform

---

base.yaml
base_drycontact.yaml
base_secplusv1.yaml

Due to how esphome handles inheritance, merging and replacing in packages[[link](https://esphome.io/guides/configuration-types.html#packages)], having _ota:_ as part of the base package will override any changes a user may make in their own config. 
So in the case of _ota:_ if you have a password defined as below in their local config:
```
ota:
- platform: esphome
password: "***"
```
They will no longer be able to update as the package will overwrite the entire _ota:_ section with what is in the base config, and result in the following error:
```
INFO Uploading /data/build/left-garage-door/.pioenvs/left-garage-door/firmware.bin (620640 bytes)
INFO Compressed to 417852 bytes
ERROR ESP requests password, but no password given!
```
So the option is either disable the OTA password by plugging …

Add ID to OTA to allow extension for overrides

---

components/ratgdo/dry_contact.cpp
components/ratgdo/dry_contact.h
components/ratgdo/ratgdo.cpp
components/ratgdo/ratgdo.h

* Don't compile any dry-contact code unless PROTOCOL_DRYCONTACT is defined.
* Use BinarySensor instead of GPIOBinarySensor to allow the user to use a template binary sensor (or any other type) if they wish. This is the recommendation of the ESPHome maintainers, and also aligns the C++ code with the Python configuration code (which will accept any type of binary sensor).
Closes #264.

Improve compatibility for non-dry-contact configurations.

---

components/ratgdo/secplus1.cpp

This PR fixes the wall panel detection process, and should address #235 #254 #272 
This is in lieu of the nuclear option #304

Wall panel detection

---

.github/workflows/build.yml
static/v32board_drycontact.yaml

Quick typo fix, I believe these are the only reference out of place. This lines the v32 dry contact board naming up with the other types.
If we really do want to make it consistent for the model names, it should probably be `ratgdo32` for all three (sec+ builds as well) :innocent: I'll make a commit for that if we want.

Correct ID and friendlyname for v32 drycontact yaml

---

static/v32board.yaml
static/v32board_drycontact.yaml
static/v32board_secplusv1.yaml

I probably should have proposed this as part of https://github.com/ratgdo/esphome-ratgdo/pull/397 rather than following convention. The v32 boards are documented as `ratgdo32` and `ratgdo32disco`, makes sense to have the yaml names reflect this.

Change ID and friendlyname of v32 boards to better match branding

---

components/ratgdo/ratgdo.cpp
components/ratgdo/secplus1.cpp
components/ratgdo/secplus2.cpp

This PR completes the C++20 lambda capture fixes that were started in #433. Several lambdas were still missing explicit captures, causing compilation failures with the newer ESPHome toolchain.
Fixed implicit lambda captures in the following locations:
- Line 102: Added `index` to capture list for `wall_panel_emulation` callback
- Line 605: Added `position` to capture list for `door_move_to_position` callback
- Line 752: Added `state` to capture list in `subscribe_door_state` defer callback
- Line 755: Added `position` to capture list in `subscribe_door_state` defer callback
- Line 113: Added `start`, `delay`, `tries` to capture list for `sync_helper` callback
- Line 179: Added `action` to capture list for `door_command` callback
- Line 207: Added `kind` to capture list for …

Fix remaining C++20 implicit lambda captures

---

components/ratgdo/secplus2.cpp

This PR fixes a lambda capture issue that was missed in previous PRs #433 and #440. The outer lambda in `Secplus2::door_command` was not capturing the `action` parameter, which caused compilation errors when the inner lambda tried to access it.

Fix remaining lambda capture issue in secplus2.cpp

---

base.yaml
base_drycontact.yaml
base_secplusv1.yaml
components/ratgdo/cover/__init__.py
components/ratgdo/lock/__init__.py

This PR updates the esphome-ratgdo component to use the new ESPHome schema functions, replacing deprecated uppercase schema constants that will be removed in ESPHome 2025.11.0.
- Updated `lock.LOCK_SCHEMA` → `lock.lock_schema()` in `components/ratgdo/lock/__init__.py`
- Updated `cover.COVER_SCHEMA` → `cover.cover_schema()` in `components/ratgdo/cover/__init__.py`
- Set minimum ESPHome version to `2025.6.0` in all base YAML files:
- `base.yaml`
- `base_drycontact.yaml`
- `base_secplusv1.yaml`
ESPHome is deprecating the uppercase schema constants (e.g., `LOCK_SCHEMA`, `COVER_SCHEMA`) in favor of lowercase function calls (e.g., `lock_schema()`, `cover_schema()`). These deprecated schemas will be completely removed in ESPHome 2025.11.0.
This change ensures the ratgdo component remains …

fix: update deprecated ESPHome schemas for 2025.6.0 compatibility

---

components/ratgdo/ratgdo.cpp

Reverts ratgdo/esphome-ratgdo#447
closes #448

Revert "Fix lambda capture initializer warnings in subscribe methods on older ESPHome versions"

---

base.yaml
base_drycontact.yaml
base_secplusv1.yaml
components/ratgdo/__init__.py
static/customized_examples/v32board_gate_party_mode.yaml
static/v32board.yaml
static/v32board_drycontact.yaml
static/v32board_secplusv1.yaml
static/v32disco.yaml
static/v32disco_drycontact.yaml
static/v32disco_secplusv1.yaml

In configurations with only one instance of the 'ratgdo' component (nearly all of them), there is no need for the entity configurations to specify the ID of the component, as the schema can auto-detect it.

Simplify configuration by auto-detecting ratgdo_id
